### ISSUE TITLE
Codacy の導入

### ISSUE THREAD

**Issue by kinari321** [sunabak0/akiyadego-kotlin#8]
https://www.codacy.com/

**Comment by kinari321** [comment]
[Install and authorize Codacy](https://app.codacy.com/gitHubApps/installGitHubApps/gh)をクリック

![image](https://user-images.githubusercontent.com/43948442/205398205-39becfc2-e59b-4494-8c5d-064228fd8420.png)

**Comment by kinari321** [comment]
「Only select repositories」で以下リポジトリを選択
- sunabak0/akiyadego-openapi
- sunabak0/akiyadego-kotlin

![image](https://user-images.githubusercontent.com/43948442/205398364-afa4e38d-7472-4bcb-9474-7fb1d3aca487.png)

**Comment by sunakan** [comment]
こんなメールが来る

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/205398627-26f9aa15-ae46-4281-8e77-77dfed4687a1.png">

**Comment by sunakan** [comment]
Approve, Install, & Authorizeをクリック

<img width="300" alt="image" src="https://user-images.githubusercontent.com/43210698/205398719-fd8631f7-9746-4159-9109-c93415e62418.png">

**Comment by kinari321** [comment]
「Add Repository」で追加
- sunabak0/akiyadego-openapi
- sunabak0/akiyadego-kotlin

![image](https://user-images.githubusercontent.com/43948442/205399054-653980fe-bdbe-45d8-a8b1-a7f38c7f672e.png)

**Comment by kinari321** [comment]
導入Done!
https://app.codacy.com/gh/sunabak0/akiyadego-kotlin/dashboard

**Comment by kinari321** [comment]
「[View more details on Codacy Production](https://app.codacy.com/gh/sunabak0/akiyadego-kotlin/pullRequest?prid=10691613)」
こんな感じで提案が見れる

![スクリーンショット 2022-12-03 11 35 56](https://user-images.githubusercontent.com/43948442/205418433-3fdc85a5-76ca-4cc6-ab8c-841da1c1c08c.png)
