### ISSUE TITLE
Makefile の make git.update-submodule コマンドの更新

### ISSUE THREAD

**Issue by kinari321** [sunabak0/akiyadego-kotlin#91]
[akiyadego-openapi](https://github.com/sunabak0/akiyadego-openapi/blob/main/openapi.yml) の更新し、`$ make git.update-submodule`コマンドをしたときに実際に更新されなかった問題を解決する。

https://github.com/sunabak0/akiyadego-kotlin/blob/24a5f9fe1b7f324f266bf8cf929188756d9c4d99/Makefile#L34-L39

**Comment by sunakan** [comment]
オプションだけで済むならそれでお願いしたいです

**Comment by kinari321** [comment]
`$ git submodule update --init --recursive` から
`$ git submodule foreach git pull origin main` のみに変更してみました。
ちょっと自信がないので、QA 作業も合わせてしていただけると助かります。

**Comment by sunakan** [comment]
レビューコメントしました

PR に issue を付与してくださると嬉しいです
